kind: Deployment
apiVersion: apps/v1
metadata: 
  name: deployment-srvc

spec:
  replicas: 2
  selector:
    matchLabels:
      service: srvc

  template:
    metadata:
      labels:
        service: srvc

    spec:
      containers:
        - name: v1
          image: manishramdhave/srvc:1.0
          ports:
            - containerPort: 8080
