kind: Deployment
apiVersion: apps/v1
metadata: 
  name: deployment-service

spec:
  replicas: 2
  selector:
    matchLabels:
      service: service

  template:
    metadata:
      labels:
        service: service

    spec:
      containers:
        - name: v1
          image: manishramdhave/service:1.0
          ports:
            - containerPort: 8080
