kind: Deployment
apiVersion: apps/v1
metadata: 
  name: deployment-svc

spec:
  replicas: 2
  selector:
    matchLabels:
      service: svc

  template:
    metadata:
      labels:
        service: svc

    spec:
      containers:
        - name: v1
          image: manishramdhave/svc:1.1
          ports:
            - containerPort: 8080
